### ISSUE TITLE
Support editing

### ISSUE THREAD

**Issue by chaorace** [amake/orgro#6] opened 2020-06-07 16:09 UTC
Currently, it seems the app only allows for viewing of org files. Are there any plans to provide write functionality in the app? If so, perhaps we should figure out a roadmap of desirable editing features to provide?

**Comment by son1112** [comment] 2020-06-07 19:49
I'm curious about this as well. Would love to be able to create and edit org files using this application. It's the best org viewer for mobile yet, IMO!

**Comment by amake** [comment] 2020-06-08 02:22
Thanks for the request. Here's what I wrote about editing previously:

Editing would be a very big stretch goal. File access I don’t think is the main hurdle. Off the top of my head the main barriers are:

- Medium difficultly: Ensuring faithful round-trip from text to parsed representations and back to text. I wouldn’t want to mangle files or make spurious changes, but I didn’t design the parser with round-tripping in mind, so that might be hard.
- Very hard difficulty: Making a good interface for editing. The display is not one big text buffer with styling like in Emacs, it’s a bunch of separate UI components (“widgets” in Flutter parlance). So editing can’t be as simple as placing a cursor and typing, which is probably not very desirable on mobile anyway. It will be hard just to design a usable interface; implementing it may be even harder—it could require completely reimplementing the current UI.

That said, I may get the itch to do something a bit smaller in scope, such as allowing checking checkboxes or toggling todo status.

**Comment by amake** [comment] 2020-06-08 03:32
[Markor](https://github.com/gsantner/markor) has been suggested as inspiration for implementing editing.

**Comment by shombando** [comment] 2020-06-08 03:49
> [Markor](https://github.com/gsantner/markor) has been suggested as inspiration for implementing editing.
Also suggesting [Organice](https://github.com/200ok-ch/org-parser/pull/18) `org-parser` as parsing tool.

**Comment by amake** [comment] 2020-06-08 03:55
I made my [own parser for Orgro](https://github.com/amake/org_parser) in Dart. [Organice's org_parser](https://github.com/200ok-ch/org-parser) is written in Clojure, and I can't see any path to making that run on iOS, so it's a non-starter as a *replacement*. It could be useful as inspiration for e.g. AST representation.

**Comment by macdonaldster** [comment] 2020-06-08 03:55
My attraction to this software is I can quickly view org files on my mobile device. I don't necassarily want to edit. I am liking the fact that a simple "git pull" (e.g. using Mgit) gets my latest files without messing with conflict resolution because of something Orgzly did to my files (NOTHING against Orgzly - love it, but it can complicate workflow). I can see something like "org capture" that appends a headline with some other data (e.g. default TODO state, scheduled "today", etc). This would make it perfectly usable for me. N = 1, of course. I was thinking a separate app that only did that formatted append might be useful (I am guessing I could gear up something with Automate or Tasker to do this pretty easily).

**Comment by amake** [comment] 2020-06-08 03:58
> I can see something like "org capture" that appends a headline with some other data (e.g. default TODO state, scheduled "today", etc).

Sure, "just support appending new sections" is a useful reduction in scope that would be easier than supporting general editing.

**Comment by shombando** [comment] 2020-06-08 03:59
> I can see something like "org capture" that appends a headline with some other data (e.g. default TODO state, scheduled "today", etc). This would make it perfectly usable for me. N = 1, of course.

N=2, that is a great idea and goes along with @amake's comment on each node being a flutter widget. All the existing nodes can be read-only and allow a "capture" of a new node in plain text as an append to the file. Once the file is saved and rendered then any org formatting that was typed in will be displayed as intended!

**Comment by chaorace** [comment] 2020-06-08 04:02
No problem from me regarding targeting simple section appending. That covers my use-case for a desktop GTD + mobile companion workflow.

If we're going with appending new sections as the target functionality though... I would like to chip in a request to be able to also cycle TODO states.

**Comment by snuffop** [comment] 2020-06-09 16:01
What about passing the file to an editor? and re reading on save or change.  thus allowing the use of next|own cloud  dropbox or other to handle the sync   editor of choice to edit  and orgro to view.

**Comment by bradyt** [comment] 2021-01-30 06:46
Maybe you can toggle the mode, so that wherever "point" is, you toggle to edit mode which takes you to a plain text version of the file, no parsing, and you're positioned to edit the same text where you were at previously, up to glitches. Then edit, save, and toggle back to parsed view. I've also wondered if there's a way to pass "point" to open the file in an external editor.

**Comment by amake** [comment] 2021-02-01 12:19
The main issue I see with doing a bimodal editing scheme like that is that for large documents parsing is already very slow. So either the UX would become quite poor for large documents, or I have to create the machinery to allow editing partial subtrees of the document. The latter could work, but right now the parsed representation doesn't remember its exact text representation, so the round trip would have to be lossy.

**Comment by P4ndemic** [comment] 2022-08-17 11:16
maybe there can be certain forms of editing that are "easier".

So rather than allowing free text editing, have some predefined edit actions and only go for the ones that give most value with least effort.

Here are in my opinion the most valuable edit actions aside from free flow typing text:
- refiling a heading to a different heading
- marking a todo as done / changing the todo state of a heading
- adding a heading underneath another heading / at the bottom of the file

Maybe those can be achieved without having to deal with difficult UI where you need to free render text but rather only change one flutter element per edit action the user can take

**Comment by amake** [comment] 2023-01-16 10:43
> - Medium difficultly: Ensuring faithful round-trip from text to parsed representations and back to text. I wouldn’t want to mangle files or make spurious changes, but I didn’t design the parser with round-tripping in mind, so that might be hard.

I've been playing with this a bit and I find that it's quite cumbersome to adjust org_parser to retain all whitespace.

What is the best practice for parsing with an eye to retaining the original document verbatim? If there was a clear pattern to adopt, that would probably help.

Another thought is that there should really be a tree-parser grammar for Org syntax; tree-sitter seems more suited to this application and the parser produced could be used pretty much everywhere.

**Comment by amake** [comment] 2023-01-18 05:43
Relevant discussion: https://github.com/petitparser/dart-petitparser/discussions/142

**Comment by amake** [comment] 2023-08-31 23:07
Update: I've gotten org_parser to the point where it can successfully round-trip verbatim some well-formed Org documents.

The next hurdle is how to implement programmatic editing of the AST. Currently the AST is immutable. The easy thing would be to allow mutation, but I'm also looking into zippers.

- https://en.wikipedia.org/wiki/Zipper_(data_structure)
- https://stanch.github.io/reftree/talks/Immutability.html
- https://github.com/fmardini/zipper

**Comment by amake** [comment] 2023-09-11 13:46
Initial support for editing will be in v1.32.0. Look for it soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by amake** [comment] 2023-09-12 22:15
v1.32.0 is now available for beta testing at the above links.

**Comment by amake** [comment] 2023-09-15 22:49
v1.32.0 is now released on the App Store and Google Play. It will be on F-Droid whenever the next build cycle completes.

**Comment by amake** [comment] 2023-09-15 23:00
v1.33.0 will soon be available for beta testing:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

It adds undo/redo, and a prompt to share unsaved changes if they can't be saved back to the original file.

**Closed** 2023-09-27 11:08 UTC
Labels: enhancement
