### ISSUE TITLE
Extra blank lines 

### ISSUE THREAD

**Issue by llcc** [amake/orgro#107] opened 2024-10-02 09:22 UTC
1. An extra blank line exists between PROPERTIES and user-defined drawer.
2. Multiple blank lines or spaces exist after image display if no normal text followed.

**Comment by llcc** [comment] 2024-10-05 06:51
Some of the extra spaces/lines patterns are listed below. Hope that it helps to debug the issue.

```org
#+TITLE: Orgro space issues

* Properties
:PROPERTIES:
:STYLE:    a
:END:
:LOGBOOK:
CLOCK: [2024-10-02 Sat 08:49]--[2024-10-02 Sat 08:49] =>  0:00
:END:

* Images related
** No spaces
https://orgro.org/assets/appicon.png
** No spaces

https://orgro.org/assets/appicon.png

Normal text
** No spaces

https://orgro.org/assets/appicon.png
#+CAPTION: a table
| a | b | c |
|---+---+---|
| 1 | 2 | 3 |
** No spaces

https://orgro.org/assets/appicon.png
- a list
  
** No spaces

- a item
  https://orgro.org/assets/appicon.png
- b item  

** Extra spaces
https://orgro.org/assets/appicon.png

** Extra spaces

https://orgro.org/assets/appicon.png

#+CAPTION: a table
| a | b | c |
|---+---+---|
| 1 | 2 | 3 |

** Extra spaces

https://orgro.org/assets/appicon.png

- a list
  
** Extra spaces

- a item
  https://orgro.org/assets/appicon.png
  
- b item  
  
** Extra spaces
https://orgro.org/assets/appicon.png

https://orgro.org/assets/appicon.png

** End 
```

**Comment by amake** [comment] 2024-10-05 09:43
Thanks for this.

To be clear, I do consider rendering differences to be bugs. However I am rarely very motivated to fix them because they are often very hard to identify, much less fix, and they are usually not very detrimental to use of the program.

The first step is definitely identifying exactly what markup results in rendering differences, so your contribution here is very useful.

The large space after after images (equal to the height of the image) is, in my opinion, a bug in Flutter that I have reported here: https://github.com/flutter/flutter/issues/156268

But there's a chance that they consider it to be correct, so I will look for a workaround.

**Comment by amake** [comment] 2024-10-09 00:26
My report was a duplicate of https://github.com/flutter/flutter/issues/146407, which has been open for 6 months with no movement, so I put in a workaround.

I also fixed the extra line after the drawer. Look for v1.43.0 to be ready for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by llcc** [comment] 2024-10-09 01:07
@amake Thank you, that was quick.

**Closed** 2024-10-13 15:05 UTC
Labels: bug
