### ISSUE TITLE
Orgro shows up even if the file is unsupported

### ISSUE THREAD

**Issue by TriStaRvOiD** [amake/orgro#62] opened 2022-03-26 13:23 UTC
Orgro supports text files only. But I have noticed that it comes as an option in the "Open with" window of the system, no matter what type of file it is.

https://user-images.githubusercontent.com/58824912/160241428-310fd600-1c48-4673-acfe-41cbc71fc5c8.mp4

Orgro should only show up if it actually supports the file.

**Comment by amake** [comment] 2022-03-26 13:27
This is a duplicate of #58

**Closed** 2022-03-26 13:27 UTC

**Comment by TriStaRvOiD** [comment] 2022-03-26 13:30
> This is a duplicate of #58

I had noticed that, but didn't really understand what it was about.
My bad

**Comment by amake** [comment] 2022-03-26 13:32
No worries. To be honest your ticket is clearer, but the other one came first. Maybe I should have closed that one.

**Comment by TriStaRvOiD** [comment] 2022-03-26 17:29
> Maybe I should have closed that one.

No need, I'll just put the stuff that I put here there as a comment
