### ISSUE TITLE
Handling of telephone numbers

### ISSUE THREAD

**Issue by TheJJ** [amake/orgro#76] opened 2023-07-21 16:31 UTC
orgro seems to have installed a android provider for contact numbers.

orgro is presented as the icons and handler for clicking contact numbers in the contact list (for calling, text messages, video calls).

orgro should not register for this, unless it actually does something useful with the contact numbers.

**Comment by amake** [comment] 2023-07-21 23:15
This is a duplicate of https://github.com/amake/orgro/issues/58#issuecomment-1646328845

**Closed by amake** 2023-07-21 23:15 UTC
