### ISSUE TITLE
Blank screen when typing in the search boxes

### ISSUE THREAD

**Issue by navigator8** [amake/orgro#119] opened 2024-11-30 12:32 UTC
App crashes when typing in the search boxes on ios

**Comment by amake** [comment] 2024-11-30 13:02
I can't reproduce this. Can you give more information?

- iOS device and version
- Orgro version
- What specific actions are you taking?
- What specifically happens? (I.e. does the app actually disappear and you get kicked back to the home screen, or does the app remain on screen but go blank, etc.?)

**Comment by amake** [comment] 2024-11-30 13:27
Actually I think I may have figured this out.

If your document contains a date-only timestamp like `[2024-11-30]`, there is an error that results in a blank gray screen when a non-matching search query is checked against it.

I will have a fix ready shortly.

**Comment by navigator8** [comment] 2024-11-30 13:51
Thanks, yes, I am getting a gray screen.

**Comment by amake** [comment] 2024-11-30 14:20
This will be fixed in v1.48.3, ready for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by amake** [comment] 2024-12-02 02:38
The fix is released on the App Store and Google Play. F-Droid is pending.

**Comment by amake** [comment] 2024-12-10 12:04
This is now fixed everywhere.

**Closed by amake** 2024-12-10 12:04 UTC
Labels: bug
